generador_URDF:
  ros__parameters:
    fisico.cuerpo.dim: [0.2, 0.2, 0.05] # [x, y, z] en metros
    fisico.cuerpo.color: "White"      # Empezando en mayúscula

    fisico.cuerpo.masa: 1.0             # en kg
    fisico.cuerpo.matriz_inercia: [1e-4, 1e-4, 1e-4, 0.0, 0.0, 0.0]  # [ixx, iyy izz, ixy, ixz, iyz]

    fisico.brazos.numero: 4           # 4, 6 u 8
    fisico.brazos.grados: 45.0        # grados respecto al frente 
    fisico.brazos.dim: [0.25, 0.01]     # longitud (respecto al centro del cuerpo) y radio en metros
    fisico.brazos.color: "Gray"       # Empezando en mayúscula

    fisico.brazos.masa: 0.05          # en kg
    fisico.brazos.matriz_inercia: [1e-5, 1e-5, 1e-5, 0.0, 0.0, 0.0]  # [ixx, iyy izz, ixy, ixz, iyz]
    
    fisico.motores.dim: [0.02, 0.02]     # altura y radio en metros
    fisico.motores.color: "Green"       # Empezando en mayúscula

    fisico.motores.masa: 0.05         # en kg
    fisico.motores.matriz_inercia: [1e-5, 1e-5, 1e-5, 0.0, 0.0, 0.0] # [ixx, iyy izz, ixy, ixz, iyz]





    sensores.camara.estereo: true     # true: estéreo || false: mono
    




    plugin.camara.topico.imagen: "sensor/camera/image_raw"
    plugin.camara.topico.info: "sensor/camera/camera_info"
